### ISSUE TITLE
How to handle branch merges with this plugin?

### ISSUE THREAD

**Issue by mklueh** [nicolasfara/conventional-commits#130]
When you merge one branch into another, git will create messages like **`Merged branch 'master' into xyz`**, which obviously does not match the conventional commit pattern.

What is the general approach using this plugin? Is it possible to exclude those?

**Comment by nicolasfara** [comment]
Hi @mklueh,

The best approach I could suggest is to use rebase instead of merge as a merge method for a branch.
Using the rebase you don't have a merge commit and the history is linear. In this case, the plugin works fine.

Currently, there aren't any methods to "suppress" the check. But I will investigate a way to suppress the check, somehow :)

If you want to use the **merge** as a merge strategy, you could modify the commit message to make it conventional commit compliant. For example, if the merge commit is the last one in the local history, you could modify it with `git commit --amend" and edit the commit message (**chore: Merge branch 'master' into XYZ**).

**Comment by mklueh** [comment]
@nicolasfara Thank you!

Not sure if rebasing is an option in our case. Adjusting the commit message could be an idea :)

Would it be possible to exclude merges from the hook in general? For example, current scenario:

One college merged a non-conventional commit into master, because the plugin is currently not on master.

I try to merge master into my branch, and the plugin complains that merging is not possible because of non-conventional commits.

Now in order to get it merged, I had to go to .git/hooks and delete the hook of the plugin.

Would it make sense to ignore those merges and just focus on "normal" local commits?

**Comment by kmbisset89** [comment]
I am also running into something like this trying to use the plugin. My CI/CD is failing in my GitLab MR because it cannot get the hook messages.

**Comment by nicolasfara** [comment]
I tried to fix this issue by releasing a new plugin version that makes it possible to configure a regex so that if a commit message matches it, the check succeeds.

Please don't hesitate to reopen this issue if there are problems with this approach.

The settings key added is `ignoreCommitMessage` and a regex should be specified.
